version: '3'
services:
  bot1:
    build: ./bot-1
    ports:
      - "5000:5000"
  bot2:
    build: ./bot-01
    ports:
      - "5001:5001"
  bot3:
    build: ./bot-02
    ports:
      - "5002:5002"
  bot4:
    build: ./bot-03
    ports:
      - "5003:5003"